"""initial database migration

Revision ID: 82bab75eaa5e
Revises:
Create Date: 2020-01-20 00:12:46.202866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bab75eaa5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(length=20), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('update_time', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('price')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    # ### end Alembic commands ###
